- dockerImage: instill-ai/destination-numbers
  spec:
    documentationUrl: https://www.instill.tech/docs/destination-connectors/numbers-protocol
    connectionSpecification:
      $schema: http://json-schema.org/draft-07/schema#
      additionalProperties: false
      properties: {}
      required: []
      title: NumbersProtocol Destination Connector Spec
      type: object
    supportsIncremental: false
    supportsNormalization: false
    supportsDBT: false
    supported_destination_sync_modes: []
