- dockerImage: instill-ai/destination-nit
  spec:
    documentationUrl: https://docs.numbersprotocol.io/introduction/numbers-protocol
    connectionSpecification:
      $schema: http://json-schema.org/draft-07/schema#
      required:
        - "creatorName"
        - "license"
      additionalProperties: true
      properties:
        creatorName:
          title: "Creator Name"
          description: "The Asset Creator Name display on https://nftsearch.site"
          type: "string"
          order: 1
        license:
          title: "License"
          type: "string"
          description: "The License display on https://nftsearch.site"
          order: 2
      title: NumbersProtocol NIT Destination Connector Spec
      type: object
    supportsIncremental: false
    supportsNormalization: false
    supportsDBT: false
    supported_destination_sync_modes: []
