- name: NIT
  uid: 70d8664a-d512-4517-a5e8-5d4da81756a7
  dockerRepository: instill-ai/destination-nit
  dockerImageTag: ""
  documentationUrl: hhttps://docs.numbersprotocol.io/introduction/numbers-protocol
  releaseStage: generally_available
