- name: HTTP
  uid: 909c3278-f7d1-461c-9352-87741bef11d3
  dockerRepository: instill-ai/destination-http
  dockerImageTag: ""
  documentationUrl: https://www.instill.tech/docs/destination-connectors/http
  icon: http.svg
  releaseStage: generally_available
- name: gRPC
  uid: c0e4a82c-9620-4a72-abd1-18586f2acccd
  dockerRepository: instill-ai/destination-grpc
  dockerImageTag: ""
  documentationUrl: https://www.instill.tech/docs/destination-connectors/grpc
  icon: grpc.svg
  releaseStage: generally_available
